### ISSUE TITLE
Make migrate fails at first migration

### ISSUE THREAD

**Issue by vkaracic** [openedx/course-discovery#156]
When I try to run `make migrate` I get this error on a fresh install on latest master:

```
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vedran/Develop/course-discovery/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/vedran/Develop/course-discovery/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vedran/Develop/course-discovery/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vedran/Develop/course-discovery/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/vedran/Develop/course-discovery/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/vedran/Develop/course-discovery/lib/python3.4/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/home/vedran/Develop/course-discovery/lib/python3.4/site-packages/django/db/migrations/executor.py", line 154, in apply_migration
    self.recorder.record_applied(migration.app_label, migration.name)
  File "/home/vedran/Develop/course-discovery/lib/python3.4/site-packages/django/db/migrations/recorder.py", line 67, in record_applied
    self.migration_qs.create(app=app, name=name)
  File "/home/vedran/Develop/course-discovery/lib/python3.4/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/vedran/Develop/course-discovery/lib/python3.4/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/vedran/Develop/course-discovery/lib/python3.4/site-packages/django/db/models/base.py", line 771, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/vedran/Develop/course-discovery/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/vedran/Develop/course-discovery/lib/python3.4/site-packages/haystack/signals.py", line 51, in handle_save
    index = self.connections[using].get_unified_index().get_index(sender)
  File "/home/vedran/Develop/course-discovery/lib/python3.4/site-packages/haystack/utils/loading.py", line 112, in __getitem__
    self._connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
  File "/home/vedran/Develop/course-discovery/lib/python3.4/site-packages/haystack/utils/loading.py", line 65, in load_backend
    return import_class(full_backend_path)
  File "/home/vedran/Develop/course-discovery/lib/python3.4/site-packages/haystack/utils/loading.py", line 32, in import_class
    module_itself = importlib.import_module(module_path)
  File "/home/vedran/Develop/course-discovery/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'course_discovery.apps.core.haystack_backends'
Makefile:58: recipe for target 'migrate' failed
make: *** [migrate] Error 1
```

This is the migration that is failing: https://github.com/django/django/blob/master/django/contrib/contenttypes/migrations/0001_initial.py
I don't know why a Django migration should fail here?

**Comment by vkaracic** [comment]
I had haystack adjustments in my private.py that caused this. Works when I remove them. Carry on.
