### ISSUE TITLE
TransportError(404, 'IndexMissingException[[*] missing]') running make migrate

### ISSUE THREAD

**Issue by ghost** [openedx/course-discovery#861]
I'm using **edxapp open-release/ficus.master** on **ubuntu 16.04**. When doing ` make migrate` on discovery version [`master`, `2017-03-03`, `release-2017-02-28`..]  the migration passes fine but i'm getting
 
> elasticsearch.exceptions.NotFoundError: TransportError(404, 'IndexMissingException[[*] missing]')

 while doing

> python manage.py install_es_indexes'

Output below 

> python manage.py migrate --noinput

(....)
`
2017-04-26 18:42:47,134 INFO 15186 [course_discovery.apps.core.management.commands.install_es_indexes] /edx/app/discovery/discovery/course_discovery/apps/core/management/commands/install_es_indexes.py:19 - Attempting to establish initial connection to Elasticsearch host [http://127.0.0.1:9200/]...
2017-04-26 18:42:47,134 INFO 15186 [course_discovery.apps.core.management.commands.install_es_indexes] /edx/app/discovery/discovery/course_discovery/apps/core/management/commands/install_es_indexes.py:21 - ...success!
2017-04-26 18:42:47,134 INFO 15186 [course_discovery.apps.core.utils] /edx/app/discovery/discovery/course_discovery/apps/core/utils.py:12 - Making sure alias [catalog] exists...
2017-04-26 18:42:47,138 WARNING 15186 [elasticsearch] /edx/app/discovery/venvs/discovery/lib/python3.5/site-packages/elasticsearch/connection/base.py:82 - HEAD /_alias/catalog [status:404 request:0.003s]
2017-04-26 18:42:47,138 WARNING 15186 [elasticsearch] /edx/app/discovery/venvs/discovery/lib/python3.5/site-packages/elasticsearch/connection/base.py:82 - HEAD /_alias/catalog [status:404 request:0.003s]
2017-04-26 18:42:47,188 INFO 15186 [course_discovery.apps.core.utils] /edx/app/discovery/discovery/course_discovery/apps/core/utils.py:23 - ...index [catalog_20170426184247] created.
2017-04-26 18:42:47,192 WARNING 15186 [elasticsearch] /edx/app/discovery/venvs/discovery/lib/python3.5/site-packages/elasticsearch/connection/base.py:82 - POST /_aliases [status:404 request:0.004s]
2017-04-26 18:42:47,192 WARNING 15186 [elasticsearch] /edx/app/discovery/venvs/discovery/lib/python3.5/site-packages/elasticsearch/connection/base.py:82 - POST /_aliases [status:404 request:0.004s]
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/edx/app/discovery/venvs/discovery/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/edx/app/discovery/venvs/discovery/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/edx/app/discovery/venvs/discovery/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/edx/app/discovery/venvs/discovery/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/edx/app/discovery/discovery/course_discovery/apps/core/management/commands/install_es_indexes.py", line 23, in handle
    ElasticsearchUtils.create_alias_and_index(es, alias)
  File "/edx/app/discovery/discovery/course_discovery/apps/core/utils.py", line 32, in create_alias_and_index
    es.indices.update_aliases(body)
  File "/edx/app/discovery/venvs/discovery/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/edx/app/discovery/venvs/discovery/lib/python3.5/site-packages/elasticsearch/client/indices.py", line 465, in update_aliases
    params=params, body=body)
  File "/edx/app/discovery/venvs/discovery/lib/python3.5/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/edx/app/discovery/venvs/discovery/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/edx/app/discovery/venvs/discovery/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, 'IndexMissingException[[*] missing]')
Makefile:70: recipe for target 'migrate' failed
make: *** [migrate] Error 1
`

This error was mentioned before on the slack channel but still no answer for it, just a hack

**Comment by clintonb** [comment]
This service is not supported for Ficus. My guess is you have not configured Elasticsearch.

We will add support for this service in the Ginkgo release.
